import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin']});

export default function Home() {

  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.loginScreen}>
        <div className={styles.loginImg}>

        </div>
        
        <section className={styles.login}>
          <Image 
            className={styles.locker}
            src='/images/locker.svg'
            width={200}
            height={200}
          />
          <h1 className={`${inter.className} ${styles.h1}`}>LOGIN</h1>
          <form className={styles.form}>
          <label 
            for="email"
            className={`${inter.className}`}
          >Usuário
          </label>
          <input 
            type='email'
            name="email"
            className={`${inter.className} ${styles.userName}`}
            placeholder='usuario@email.com.br'
          />

          <label 
            for="password"
            className={`${inter.className}`}
          >
          Senha</label>
          <input 
            type='password'
            name="password"
            className={`${inter.className} ${styles.userPassword}`}
            placeholder='********************'
          />

          <Link
            className={`${styles.loginButton} ${inter.className}`}
            type='submit'
            href='/dashboard'
            
          >
          LOGIN</Link>
          
          <Link 
            className={`${inter.className} ${styles.forgotPassword}`}
            href='/'
          >
            
            Esqueceu a Senha ?</Link>
        </form>
        </section>
        
      </main>
    </>
    
  )
}
